# Rename this file to secret.yaml and change the last line with the password
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/git-0: https://git.haenerconsulting.com
    tekton.dev/docker-0: https://docker.haenerconsulting.com
type: kubernetes.io/basic-auth
stringData:
  username: buildbot
  password: CHANGEME
